name: Create Archive
on:
  push:
    tags:
      - "1.*.*"
jobs:
  release:
    name: Release GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/release-github-actions@v6
